"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class command_t(object):
    __slots__ = ["is_start", "is_stop"]

    def __init__(self):
        self.is_start = False
        self.is_stop = False

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.is_start, self.is_stop))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = command_t()
        self.is_start, self.is_stop = struct.unpack(">bb", buf.read(2))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if command_t in parents: return 0
        tmphash = (0x120295601862a1c5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if command_t._packed_fingerprint is None:
            command_t._packed_fingerprint = struct.pack(">Q", command_t._get_hash_recursive([]))
        return command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

