"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class plan_t(object):
    __slots__ = ["robot_id", "robot_num", "num_step", "steps"]

    def __init__(self):
        self.robot_id = 0
        self.robot_num = 0
        self.num_step = 0
        self.steps = []

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(plan_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iii", self.robot_id, self.robot_num, self.num_step))
        buf.write(struct.pack('>%di' % self.num_step, *self.steps[:self.num_step]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != plan_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return plan_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = plan_t()
        self.robot_id, self.robot_num, self.num_step = struct.unpack(">iii", buf.read(12))
        self.steps = struct.unpack('>%di' % self.num_step, buf.read(self.num_step * 4))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if plan_t in parents: return 0
        tmphash = (0xe3f55b4a8b876cbf) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if plan_t._packed_fingerprint is None:
            plan_t._packed_fingerprint = struct.pack(">Q", plan_t._get_hash_recursive([]))
        return plan_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

